version: '3.8'

services:
  vue:
    build:
      context: .
      dockerfile: dockerfileVue
    ports:
      - "8080:5000"
    volumes:
      - ./vue-app:/app

  landing:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
